services:
  backend:
    build:
      context: ./MoviesAPI
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;
        Database=MoviesAPI;
        User ID=sa;
        Password=${SA_PASSWORD};
        TrustServerCertificate=True;
        MultipleActiveResultSets=True
      ConnectionStrings__AZURE_STORAGE_CONNECTION: ${AZURE_STORAGE_CONNECTION}
      ALLOWED_ORIGINS: "${ALLOWED_ORIGINS}"
      JWT_KEY: "${JWT_KEY}"
    depends_on:
      - azurite
    expose:
      - "8080"
    networks: [appnet]

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks: [appnet]

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./MoviesAngular/dist/MoviesAngular/browser:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/ssl:ro
    networks: [appnet]

networks:
  appnet:
    external: true

